emscripten 빌드 체크 / libktx 버전 업데이트 확인된 문제: d3d11 링크 시에만 lib 위치 잘못 세팅됨

diff --git a/externals/ktx/.github/workflows/windows.yml b/externals/ktx/.github/workflows/windows.yml
--- a/externals/ktx/.github/workflows/windows.yml
+++ b/externals/ktx/.github/workflows/windows.yml
@@ -15,8 +15,8 @@ on:
     # Also trigger on push of release tags to any branch. Useful
     # for testing release builds before merging to main.
     tags:
-      - 'v[0-9]+\.[0-9]+\.[0-9]+'
-      - 'v[0-9]+\.[0-9]+\.[0-9]+-*'
+      - 'v[0-9]+.[0-9]+.[0-9]+'
+      - 'v[0-9]+.[0-9]+.[0-9]+-*'
     paths-ignore:
       - .appveyor.yml
       - .travis.yml
@@ -31,21 +31,22 @@ jobs:
         os: [ windows-latest ]
         toolset: [v143, CLangCL]
         arch: [ x64 ]
+        check_mkvk: [ NO ]
         options: [
           {config: 'Debug,Release',
-           doc: ON, jni: ON, loadtests: OpenGL+Vulkan, tests: ON, tools: ON, tools_cts: ON,
+           doc: ON, jni: ON, loadtests: OpenGL+Vulkan, py: ON, tests: ON, tools: ON, tools_cts: ON,
            package: YES,
            sse: ON, opencl: OFF},
           {config: Release,
-           doc: OFF, loadtests: OFF, tests: OFF, tools: OFF, tools_cts: OFF,
+           doc: OFF, loadtests: OFF, py: OFF, tests: OFF, tools: OFF, tools_cts: OFF,
            package: NO,
            sse: OFF, opencl: OFF},
           {config: Release,
-           doc: OFF, loadtests: OFF, tests: OFF, tools: OFF, tools_cts: OFF,
+           doc: OFF, loadtests: OFF, py: OFF, tests: OFF, tools: OFF, tools_cts: OFF,
            package: NO,
            sse: OFF, opencl: ON},
           {config: Release,
-           doc: OFF, loadtests: OFF, tests: OFF, tools: OFF, tools_cts: OFF,
+           doc: OFF, loadtests: OFF, py: OFF, tests: OFF, tools: OFF, tools_cts: OFF,
            package: NO,
            sse: ON, opencl: ON}
         ]
@@ -56,7 +57,7 @@ jobs:
             arch: x64
             options: {
               config: 'Debug,Release',
-              doc: ON, jni: ON, loadtests: OpenGL+Vulkan, tests: ON, tools: ON, tools_cts: ON,
+              doc: ON, jni: ON, loadtests: OpenGL+Vulkan, py: ON, tests: ON, tools: ON, tools_cts: ON,
               package: NO,
               sse: ON, opencl: OFF
             }
@@ -64,11 +65,9 @@ jobs:
             generator: 'Visual Studio 17 2022'
             toolset: CLangCL
             arch: arm64
-            # No tests on arm64 since the host is x64 and can't run the
-            # built tests
             options: {
               config: 'Debug,Release',
-              doc: ON, jni: ON, loadtests: OFF, tests: ON, tools: ON, tools_cts: ON,
+              doc: ON, jni: ON, loadtests: OpenGL, py: OFF, tests: ON, tools: ON, tools_cts: ON,
               package: YES
             }
     runs-on: ${{ matrix.os }}
@@ -84,16 +83,19 @@ jobs:
       CMAKE_TOOLSET: ${{ matrix.toolset }}
 
       ARCH: ${{ matrix.arch }}
+      CHECK_MKVK: ${{ matrix.check_mkvk }}
       CONFIGURATION: ${{ matrix.options.config }}
       FEATURE_DOC: ${{ matrix.options.doc }}
       FEATURE_JNI: ${{ matrix.options.jni }}
       FEATURE_LOADTESTS: ${{ matrix.options.loadtests }}
+      FEATURE_PY: ${{ matrix.options.py }}
       FEATURE_TESTS: ${{ matrix.options.tests }}
       FEATURE_TOOLS: ${{ matrix.options.tools }}
       FEATURE_TOOLS_CTS: ${{ matrix.options.tools_cts }}
       PACKAGE: ${{ matrix.options.package }}
       SUPPORT_OPENCL: ${{ matrix.options.opencl }}
       SUPPORT_SSE: ${{ matrix.options.sse }}
+      WERROR: ON
 
       CODE_SIGN_TIMESTAMP_URL: "http://timestamp.digicert.com"
       AZURE_KEY_VAULT_URL: ${{ secrets.AZURE_KEY_VAULT_URL }}
@@ -107,18 +109,48 @@ jobs:
       OPENGL_ES_EMULATOR: C:/Imagination/Windows_x86_64
       OPENGL_ES_EMULATOR_WIN: C:\Imagination\Windows_x86_64
       PVR_SDK_HOME: https://github.com/powervr-graphics/Native_SDK/raw/master/lib/Windows_x86_64/
+      PYTHON: C:\hostedtoolcache\windows\Python\3.11.4\x64\python.exe
+      # This is set to avoid the compiler running out of heap space
+      # when vcpkg is compiling glew. Default is logical cores + 1.
+      # Runners have 1 thread per core and 2 cores.
+      VCPKG_MAX_CONCURRENCY: 2
       VULKAN_SDK_VER: 1.3.243.0
 
     steps:
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v4
       with:
         # Fetch all history to make sure tags are
         # included (used for version creation)
         fetch-depth: 0
 
+    - name: Install NSIS with large string support
+      if: matrix.check_mkvk != 'ONLY'
+      shell: bash
+      run: |
+        retryCount=4
+        success=0
+        for i in $(seq $retryCount) ; do
+            echo "Attempt no: $i"
+            stack exec -- wget -O nsis-3.08-strlen_8192.zip https://downloads.sourceforge.net/nsis/NSIS%203/3.08/nsis-3.08-strlen_8192.zip
+            if [[ $? -eq 0 ]] ; then
+                success=1
+                7z x -aoa -o"/c/Program Files (x86)/NSIS" nsis-3.08-strlen_8192.zip
+                rm nsis-3.08-strlen_8192.zip
+                echo "Installation successful."
+                break
+            else
+                echo "Installation failed. Retrying..."
+                sleep $(( 2*$i ))
+            fi
+        done
+        if (( ! $success )) ; then
+            echo "Installation failed after $retryCount attempts."
+            exit 1
+        fi
+
     - name: Force fetch provoking tag's annotation.
       # Work around https://github.com/actions/checkout/issues/290.
-      if: github.ref_type == 'tag'
+      if: github.ref_type == 'tag' && matrix.check_mkvk != 'ONLY'
       run: git fetch -f origin ${{ github.ref }}:${{ github.ref }}
 
     # Need doxygen if docs are supposed to be built.
@@ -149,6 +181,7 @@ jobs:
         }
 
     - name: Install AzureSignTool
+      if: matrix.check_mkvk != 'ONLY'
       id: install-ast
       run: |
         if ($env:PACKAGE -eq "YES" -and $env:AZURE_KEY_VAULT_URL) {
@@ -156,25 +189,49 @@ jobs:
           echo "CODE_SIGN_KEY_VAULT=Azure" >> $env:GITHUB_ENV
         }
 
+    - name: Install Dependencies for load tests on arm64
+      if: matrix.arch == 'arm64' && matrix.options.loadtests != 'OFF'
+      run: |
+        pushd $env:VCPKG_INSTALLATION_ROOT
+        ./vcpkg install SDL2:arm64-windows assimp:arm64-windows glew:arm64-windows
+        cat buildtrees\glew\install-arm64-windows-rel-out.log
+        popd
+        echo "CMAKE_TOOLCHAIN_FILE=$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" >> $env:GITHUB_ENV
+        echo "LOADTESTS_USE_LOCAL_DEPENDENCIES=ON" >> $env:GITHUB_ENV
+
     - name: Install Dependencies
+      if: matrix.check_mkvk != 'ONLY'
       # This script only installs what's needed by ON FEATUREs.
       run: ci_scripts/install_win.ps1
 
     - name: Set up JDK 17.
-      if: matrix.options.jni == 'ON'
-      uses: actions/setup-java@v3
+      if: matrix.options.jni == 'ON' && matrix.check_mkvk != 'ONLY'
+      uses: actions/setup-java@v4
       with:
         distribution: 'temurin'
         java-version: '17'
 
+    - name: Set up Python 3.11
+      if: matrix.options.py == 'ON' && matrix.check_mkvk != 'ONLY'
+      uses: actions/setup-python@v5
+      with:
+        python-version: '3.11.4'
+
+    - name: Smudge embedded dates
+      if: matrix.options.doc == 'ON'
+      run: |
+        ./install-gitconfig.ps1
+        ci_scripts/smudge_date.ps1
+
     - name: Build Windows
+      if: matrix.check_mkvk != 'ONLY'
       #   The installers run as part of "Install Dependencies" add
       # environment variables to the registry and augment $Path there.
       # Although each step gets a new Powershell instance, that instance
       # is spawned from some parent Powershell so it does not pick up
       # the changes from the registry. Use Chocolatey's helper to
       # pull in the changes.
-      #   After import `refreshenv` is an alias for
+      #   After import, `refreshenv` is an alias for
       # Update-SessionEnvironment. Without the import refreshenv will end
       # up calling the cmd.exe version, which won't help Powershell, and
       # Update-SessionEnvironment will not exist.
@@ -188,7 +245,12 @@ jobs:
         $env:JAVA_HOME=$step_java_home
         ci_scripts/build_win.ps1
 
+    - name: Test Generation of VkFormat-related files
+      if: matrix.check_mkvk == 'ONLY'
+      run: ci_scripts/check_mkvk.ps1
+
     - name: Test Windows build
+      # Tests built for arm64 can't be run as the CI runners are all x64.
       if: matrix.arch == 'x64' && matrix.options.tests == 'ON'
       run: ctest --output-on-failure --test-dir $env:BUILD_DIR -C Release
 
@@ -205,18 +267,26 @@ jobs:
 
     - name: Upload Artifact
       if: matrix.options.package == 'YES' && matrix.toolset == 'CLangCL'
-      uses: actions/upload-artifact@v3
+      uses: actions/upload-artifact@v4
       with:
         name: KTX-Software-${{env.KTX_VERSION}}-Windows-${{matrix.arch}}
         path: ${{env.BUILD_DIR}}/KTX-Software-*.exe*
 
-    - name: Upload To Release
+    - name: Upload pyktx artifacts
+      if: matrix.options.package == 'YES' && matrix.options.py == 'ON'
+      uses: kittaakos/upload-artifact-as-is@v0
+      with:
+        path: ${{env.BUILD_DIR}}/interface/python_binding/dist/
+
+    - name: Upload to Release
       uses: softprops/action-gh-release@v1
       if: matrix.options.package == 'YES' && matrix.toolset == 'CLangCL' && github.event_name == 'push' && github.ref_type == 'tag'
       with:
         draft: true
         prerelease: true
-        files: ${{env.BUILD_DIR}}/KTX-Software-*.exe*
+        files: |
+            ${{env.BUILD_DIR}}/KTX-Software-*.exe*
+            ${{env.BUILD_DIR}}/interface/python_binding/dist/pyktx-*
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
diff --git a/externals/ktx/.travis.yml b/externals/ktx/.travis.yml
--- a/externals/ktx/.travis.yml
+++ b/externals/ktx/.travis.yml
@@ -17,18 +17,19 @@ language: cpp
 
 addons:
   homebrew:
+    update: false
     packages:
     - git-lfs
     - doxygen
-    - sdl2
-    #update: true
 
 env:
   global:
     - BUILD_DIR: build
+    - CHECK_MKVK: NO
     - CHECK_REUSE: NO
     - FEATURE_TESTS: ON
     - GIT_LFS_SKIP_SMUDGE: 1
+    - HOMEBREW_NO_AUTO_UPDATE: 1
     - PACKAGE: NO
     - REL_DESC_FILE: "$BUILD_DIR/rel_desc.md"
     - VULKAN_SDK_VER: "1.3.243.0"
@@ -36,42 +37,48 @@ env:
     - VULKAN_INSTALL_DIR: "$HOME/VulkanSDK/$VULKAN_SDK_VER"
     - VULKAN_SDK: "$VULKAN_INSTALL_DIR/macOS"
     - WASM_BUILD: NO
+    - WERROR: ON
   jobs:
+    # NOTE: As least 2 configurations must be present or no macOS job is run.
     # FEATURE_TESTS is off for arm64 macOS because we can't even build
     # them during CI. CI runs on x86_64 and there is a PostBuild command
     # that attempts to execute the compiled-for-m1 tests to have gtest
     # add the list of tests to the cmake test runner.
+    #
+    # FEATURE_PY is off for arm64 macOS because we'd need a cross-compiled version
+    # of Python for it to correctly build the Python extensions (the CI
+    # runs on x86_64)
     - CONFIGURATION=Debug,Release PLATFORM=macOS ARCHS=x86_64
-      FEATURE_DOC=ON FEATURE_JNI=ON FEATURE_LOADTESTS=OpenGL+Vulkan FEATURE_TOOLS=ON
-      FEATURE_TOOLS_CTS=ON SUPPORT_SSE=ON SUPPORT_OPENCL=OFF DEPLOY_DOCS=YES PACKAGE=YES
+      FEATURE_DOC=ON FEATURE_JNI=ON FEATURE_PY=ON FEATURE_LOADTESTS=OpenGL+Vulkan FEATURE_TOOLS=ON
+      FEATURE_TOOLS_CTS=ON LOADTESTS_USE_LOCAL_DEPENDENCIES=ON SUPPORT_SSE=ON SUPPORT_OPENCL=OFF DEPLOY_DOCS=YES PACKAGE=YES
     - CONFIGURATION=Release PLATFORM=macOS ARCHS=arm64
-      FEATURE_DOC=ON FEATURE_JNI=ON FEATURE_LOADTESTS=OpenGL+Vulkan FEATURE_TESTS=OFF
+      FEATURE_DOC=ON FEATURE_JNI=ON FEATURE_PY=OFF FEATURE_LOADTESTS=OpenGL+Vulkan FEATURE_TESTS=OFF
       FEATURE_TOOLS=ON FEATURE_TOOLS_CTS=OFF SUPPORT_SSE=ON SUPPORT_OPENCL=OFF PACKAGE=YES
 
     - CONFIGURATION=Release PLATFORM=macOS ARCHS=x86_64
-      FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_LOADTESTS=OFF FEATURE_TOOLS=OFF
+      FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_PY=OFF FEATURE_LOADTESTS=OFF FEATURE_TOOLS=OFF
       FEATURE_TOOLS_CTS=OFF SUPPORT_SSE=ON SUPPORT_OPENCL=ON
     - CONFIGURATION=Release PLATFORM=macOS ARCHS=arm64
-      FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_LOADTESTS=OFF FEATURE_TESTS=OFF
+      FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_PY=OFF FEATURE_LOADTESTS=OFF FEATURE_TESTS=OFF
       FEATURE_TOOLS=OFF FEATURE_TOOLS_CTS=OFF SUPPORT_SSE=ON SUPPORT_OPENCL=ON
 
     - CONFIGURATION=Release PLATFORM=macOS ARCHS=x86_64
-      FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_LOADTESTS=OFF FEATURE_TOOLS=OFF
+      FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_PY=OFF FEATURE_LOADTESTS=OFF FEATURE_TOOLS=OFF
       FEATURE_TOOLS_CTS=OFF SUPPORT_SSE=OFF SUPPORT_OPENCL=ON
     - CONFIGURATION=Release PLATFORM=macOS ARCHS=arm64
-      FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_LOADTESTS=OFF FEATURE_TESTS=OFF
+      FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_PY=OFF FEATURE_LOADTESTS=OFF FEATURE_TESTS=OFF
       FEATURE_TOOLS=OFF FEATURE_TOOLS_CTS=OFF SUPPORT_SSE=OFF SUPPORT_OPENCL=ON
 
     - CONFIGURATION=Release PLATFORM=macOS ARCHS=x86_64
-      FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_LOADTESTS=OFF FEATURE_TOOLS=OFF
+      FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_PY=OFF FEATURE_LOADTESTS=OFF FEATURE_TOOLS=OFF
       FEATURE_TOOLS_CTS=OFF SUPPORT_SSE=OFF SUPPORT_OPENCL=OFF
     - CONFIGURATION=Release PLATFORM=macOS ARCHS=arm64
-      FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_LOADTESTS=OFF FEATURE_TESTS=OFF
+      FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_PY=OFF FEATURE_LOADTESTS=OFF FEATURE_TESTS=OFF
       FEATURE_TOOLS=OFF FEATURE_TOOLS_CTS=OFF SUPPORT_SSE=OFF
       SUPPORT_OPENCL=OFF
 
     - CONFIGURATION=Debug,Release PLATFORM=iOS
-      FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_LOADTESTS=OpenGL+Vulkan FEATURE_TOOLS=OFF
+      FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_PY=OFF FEATURE_LOADTESTS=OpenGL+Vulkan FEATURE_TOOLS=OFF
       FEATURE_TOOLS_CTS=OFF SUPPORT_SSE=OFF SUPPORT_OPENCL=OFF PACKAGE=YES
 
 jobs:
@@ -82,16 +89,26 @@ jobs:
         - CHECK_REUSE: ONLY
     - os: linux
       dist: jammy
+      addons:
+        apt:
+          packages:
+            - python3
+            - python3-venv
       compiler: gcc # clang is tested by macOS build
       env:
         # NB: This must not have the fourth component of the version number.
         - VULKAN_SDK_VER: "1.3.243"
         - CMAKE_GEN: Ninja
         - CONFIGURATION=Debug
-          FEATURE_DOC=OFF FEATURE_JNI=ON FEATURE_LOADTESTS=OpenGL+Vulkan FEATURE_TOOLS=ON
-          SUPPORT_SSE=ON SUPPORT_OPENCL=OFF
+          FEATURE_DOC=OFF FEATURE_JNI=ON FEATURE_PY=ON FEATURE_LOADTESTS=OpenGL+Vulkan FEATURE_TOOLS=ON
+          SUPPORT_SSE=ON SUPPORT_OPENCL=OFF WERROR=ON
     - os: linux
       dist: jammy
+      addons:
+        apt:
+          packages:
+            - python3
+            - python3-venv
       compiler: gcc
       #jdk: openjdk17 # Reminder to find correct way to select jdk 17
       env:
@@ -99,11 +116,16 @@ jobs:
         - VULKAN_SDK_VER: "1.3.243"
         - CMAKE_GEN: Ninja
         - CONFIGURATION=Release
-          FEATURE_DOC=ON FEATURE_JNI=ON FEATURE_LOADTESTS=OpenGL+Vulkan FEATURE_TOOLS=ON
-          SUPPORT_SSE=ON SUPPORT_OPENCL=OFF PACKAGE=YES
+          FEATURE_DOC=ON FEATURE_JNI=ON FEATURE_PY=ON FEATURE_LOADTESTS=OpenGL+Vulkan FEATURE_TOOLS=ON
+          SUPPORT_SSE=ON SUPPORT_OPENCL=OFF WERROR=ON PACKAGE=YES
     - os: linux
       arch: arm64
       dist: jammy
+      addons:
+        apt:
+          packages:
+            - python3
+            - python3-venv
       compiler: gcc
       #jdk: openjdk17
       env:
@@ -111,36 +133,36 @@ jobs:
         - VULKAN_SDK_VER: "1.3.243"
         - CMAKE_GEN: Ninja
         - CONFIGURATION=Release
-          FEATURE_DOC=ON FEATURE_JNI=ON FEATURE_LOADTESTS=OpenGL
+          FEATURE_DOC=ON FEATURE_JNI=ON FEATURE_PY=ON FEATURE_LOADTESTS=OpenGL
           FEATURE_TOOLS=ON FEATURE_TOOLS_CTS=OFF
-          SUPPORT_SSE=OFF SUPPORT_OPENCL=OFF PACKAGE=YES
+          SUPPORT_SSE=OFF SUPPORT_OPENCL=OFF WERROR=ON PACKAGE=YES
     - os: linux
       dist: jammy
       compiler: gcc
       env:
         - CMAKE_GEN: Ninja
         - CONFIGURATION=Release
-          FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_LOADTESTS=OFF
+          FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_PY=OFF FEATURE_LOADTESTS=OFF
           FEATURE_TOOLS=OFF FEATURE_TOOLS_CTS=OFF
-          SUPPORT_SSE=ON SUPPORT_OPENCL=ON PACKAGE=NO
+          SUPPORT_SSE=ON SUPPORT_OPENCL=ON WERROR=ON PACKAGE=NO
     - os: linux
       dist: jammy
       compiler: gcc
       env:
         - CMAKE_GEN: Ninja
         - CONFIGURATION=Release
-          FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_LOADTESTS=OFF
+          FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_PY=OFF FEATURE_LOADTESTS=OFF
           FEATURE_TOOLS=OFF FEATURE_TOOLS_CTS=OFF
-          SUPPORT_SSE=OFF SUPPORT_OPENCL=ON PACKAGE=NO
+          SUPPORT_SSE=OFF SUPPORT_OPENCL=ON WERROR=ON PACKAGE=NO
     - os: linux
       dist: jammy
       compiler: gcc
       env:
         - CMAKE_GEN: Ninja
         - CONFIGURATION=Release
-          FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_LOADTESTS=OFF
+          FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_PY=OFF FEATURE_LOADTESTS=OFF
           FEATURE_TOOLS=OFF FEATURE_TOOLS_CTS=OFF
-          SUPPORT_SSE=OFF SUPPORT_OPENCL=OFF PACKAGE=NO
+          SUPPORT_SSE=OFF SUPPORT_OPENCL=OFF WERROR=ON PACKAGE=NO
     - os: linux
       dist: jammy
       compiler: clang
@@ -148,8 +170,8 @@ jobs:
       env:
         - WASM_BUILD=YES
         - CONFIGURATION=Debug
-          FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_LOADTESTS=OpenGL
-          SUPPORT_SSE=OFF SUPPORT_OPENCL=OFF
+          FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_PY=OFF FEATURE_LOADTESTS=OpenGL
+          SUPPORT_SSE=OFF SUPPORT_OPENCL=OFF WERROR=ON
     - os: linux
       dist: jammy
       compiler: clang
@@ -157,8 +179,8 @@ jobs:
       env:
         - WASM_BUILD=YES
         - CONFIGURATION=Release
-          FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_LOADTESTS=OpenGL
-          SUPPORT_SSE=OFF SUPPORT_OPENCL=OFF PACKAGE=YES
+          FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_PY=OFF FEATURE_LOADTESTS=OpenGL
+          SUPPORT_SSE=OFF SUPPORT_OPENCL=OFF WERROR=ON PACKAGE=YES
 
 # Phase 1: Git clone - done automatically.
 # Phase 2: Install apt addons.
@@ -182,7 +204,7 @@ before_install:
         # when the repo owner differs from the user. For details see
         # https://github.blog/2022-04-12-git-security-vulnerability-announced/
         docker run -dit --name emscripten --user "$(id -u):$(id -g)" -v $(pwd):/src emscripten/emsdk bash
-      elif [ "$CHECK_REUSE" != "ONLY" ]; then
+      elif [ "$CHECK_REUSE" != "ONLY" -a "$CHECK_MKVK" != "ONLY" ]; then
         sudo apt-get update
       fi
       ;;
@@ -197,7 +219,7 @@ install:
       pip3 install reuse
       set +e
     fi
-    if [ "$CHECK_REUSE" != "ONLY" -a "$WASM_BUILD" != "YES" ]; then
+    if [ "$CHECK_REUSE" != "ONLY" -a "$CHECK_MKVK" != "ONLY" -a "$WASM_BUILD" != "YES" ]; then
       if [ "$TRAVIS_CPU_ARCH" = "arm64" ]; then
         # JDK was not installed on arm64 runner. Kept for reference.
         #sudo apt-get -qq install openjdk-17-jdk
@@ -216,7 +238,13 @@ install:
     fi
     ;;
   osx)
-    ./ci_scripts/install_macos.sh
+    if [ "$CHECK_REUSE" != "ONLY" -a "$CHECK_MKVK" != "ONLY" ]; then
+      if [ "$LOADTESTS_USE_LOCAL_DEPENDENCIES" = "ON" ]; then
+          brew install sdl2
+          brew install assimp
+      fi
+      ./ci_scripts/install_macos.sh
+    fi
     ;;
   esac
 
@@ -232,21 +260,19 @@ before_script:
     esac
   # Make sure embedded dates are correct.
   - ./install-gitconfig.sh
-  - rm TODO.md lib/mainpage.md pkgdoc/pages.md tools/toktx/toktx.cc
-  - git checkout TODO.md lib/mainpage.md pkgdoc/pages.md tools/toktx/toktx.cc
-  - git status
+  - ci_scripts/smudge_date.sh
 
 script:
 - |
+  set -e # Instead of trying to chain everything together with &&
+         # otherwise subsequent commands will swallow bad exit status.
   case "${TRAVIS_OS_NAME:-linux}" in
   linux)
     if [ "$CHECK_REUSE" = "YES" -o "$CHECK_REUSE" = "ONLY" ]; then
       echo "Calling reuse lint."
-      set -e  # because the if below swallows a bad exit status.
-      reuse lint
-      set +e
+      reuse --suppress-deprecation lint
     fi
-    if [ "$CHECK_REUSE" != "ONLY" ]; then
+    if [ "$CHECK_REUSE" != "ONLY" -a "$CHECK_MKVK" != "ONLY" ]; then
       if [ "$WASM_BUILD" = "YES" ]; then
         ./ci_scripts/build_wasm_docker.sh
       else
@@ -255,13 +281,25 @@ script:
     fi
     ;;
   osx)
-    if [ "$PLATFORM" = "macOS" ]; then
-      ./ci_scripts/build_macos.sh
-    else
-      ./ci_scripts/build_ios.sh
+    if [ "$CHECK_REUSE" != "ONLY" -a "$CHECK_MKVK" != "ONLY" ]; then
+      if [ "$PLATFORM" = "macOS" ]; then
+        ./ci_scripts/build_macos.sh
+      else
+        ./ci_scripts/build_ios.sh
+      fi
     fi
     ;;
   esac
+  if [ "$CHECK_MKVK" = "ONLY" ]; then
+    ci_scripts/check_mkvk.sh
+  fi
+  if [ "$DEPLOY_DOCS" = "YES" ]; then
+    # Some files in the pyktx docs have an _ prefix so Jekyll will
+    # not copy them from the gh-pages branch to the website. This
+    # file says no Jekyll files here. Treat all as ordinary files.
+    touch $BUILD_DIR/docs/html/.nojekyll
+  fi
+  set +e
 
 # See if this helps with truncated logs.
 #after_script:
@@ -294,7 +332,7 @@ before_deploy:
       # run twice. https://github.com/travis-ci/travis-ci/issues/2570 about
       # this has been open for years. What a crock!
       if [ -n "$MACOS_CERTIFICATES_P12" -a -n "$TRAVIS_TAG" -a -z "$NOTARIZED" ]; then
-        ./ci_scripts/notarize.sh $BUILD_DIR/KTX-Software-*.pkg $APPLE_ID $DEVELOPMENT_TEAM $ALTOOL_PASSWORD; export NOTARIZED="true"
+        ./ci_scripts/notarize.sh $BUILD_DIR/KTX-Software-*.pkg $APPLE_ID $DEVELOPMENT_TEAM $ALTOOL_PASSWORD && export NOTARIZED="true"
       fi
       ;;
     esac
@@ -375,11 +413,25 @@ deploy:
 
   - provider: script
     edge: true
+    # nullglob is to force a null string when there are no *.whl files.
     script: ruby ci_scripts/github_release.rb -s ${GITHUB_TOKEN} -r ${TRAVIS_REPO_SLUG} -c $REL_DESC_FILE -t ${TRAVIS_TAG} --overwrite true --draft true --prerelease true $BUILD_DIR/KTX-Software-*-*
     on:
       tags: true
       #branch: master
       condition: $PACKAGE = "YES" && $TRAVIS_TAG =~ ^v[0-9].*
+
+  # Separate deploy for pyktx because the linux runners use sh not bash
+  # for the "script" so `shopt -s nullglob; ci_scripts/github_release.rb ...`
+  # does not work to avoid passing `.../*.whl` to github_release when
+  # FEATURE_PY not ON.
+  - provider: script
+    edge: true
+    script: ruby ci_scripts/github_release.rb -s ${GITHUB_TOKEN} -r ${TRAVIS_REPO_SLUG} -c $REL_DESC_FILE -t ${TRAVIS_TAG} --overwrite true --draft true --prerelease true $BUILD_DIR/interface/python_binding/dist/*.whl
+    on:
+      tags: true
+      #branch: master
+      condition: $PACKAGE = "YES" && $TRAVIS_TAG =~ ^v[0-9].* && $FEATURE_PY = "ON"
+
 # ---------------------------------------------------------
 
 # vim:ai:ts=4:sts=2:sw=2:expandtab
